language: go
notifications:
  email: false
branches:
  only:
    - master

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - test -z "$(find . -name '*.go' -exec gofmt -d {} + | tee /dev/stderr)"
  - go list ./... | sed -e "s#^$(go list .)#.#" | xargs -n 1 go test -v -race -coverprofile=>(sed -e '1!{/^mode:/d}' > .coverprofile)

after_success:
  - goveralls -coverprofile=.coverprofile -repotoken $GOVERALLS_TOKEN
