language: go
notifications:
  email: false
branches:
  only:
    - master

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - test -z "$(find . -name '*.go' -exec gofmt -d {} + | tee /dev/stderr)"
  - go list ./... | sed -e "s#^$(go list .)#.#" | xargs -n 1 go test -v -race -coverprofile=>(sed -e '1!{/^mode:/d}' > .coverprofile)

after_success:
  - |
    if [[ -n "$GOVERALLS_TOKEN" ]]; then
      goveralls -coverprofile=.coverprofile -repotoken $GOVERALLS_TOKEN
    fi
  - |
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
      go list ./... | xargs -n 1 -I{} curl http://godoc.org/-/refresh -d path={}
    fi
